spring:
  application:
    name: POST-SERVICE  # now we will identify microservices with name of project and not with port number because it can change and name is fix

  datasource:
    url: jdbc:mysql://localhost:3306/post_micro
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true  #true because this is client and it will interact with server
    server-url:
      defaultZone: http://localhost:8761/eureka

# this microservice registered with euerka server runnning on this port http://localhost:8763/eureka